# Generated by Django 3.2.16 on 2024-05-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20230905_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='route_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
