# Generated by Django 3.2.16 on 2024-05-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_route_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='title',
            field=models.CharField(blank=True, choices=[('RSR', 'Route Sales Representative'), ('Merch', 'Merchandiser'), ('RM', 'Regional Manager'), ('DM', 'Division Manager'), ('WHM', 'Warehouse Manager'), ('WHS', 'Warehouse Supervisor'), ('WHA', 'Warehouse Associate')], default='', max_length=30),
        ),
    ]
